title: "Matteo Cavalli"

url: "https://mattao.net"

lang: "en"

default_accent: "blue"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  saas_dir: _sass
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
